### ISSUE TITLE
Preview lost switching between tabs

### ISSUE THREAD

**Issue by OlegKunitsyn** [docToolchain/diagrams.net-intellij-plugin#105]
Reproduction:
- open a project in IntelliJ
- open a code tab
- unzip [collection.zip](https://github.com/docToolchain/diagrams.net-intellij-plugin/files/7301145/collection.zip) and open as a tab
- click the code tab
- click Build or Run
- click the diagram tab
- the diagram tab in "diagrams.net editor" mode is empty
- switching between the "Text" "diagrams.net editor" has no effect

IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-88-generic
Non-Bundled Plugins: de.docs_as_co.intellij.plugin.diagramsnet (0.1.11)
Kotlin: 212-1.5.10-release-IJ5284.40
Current Desktop: ubuntu:GNOME

**Comment by ahus1** [comment]
For #201 I switched the diagram rendering to an "off-screen-rendering" mode. After that change, this was no longer reproducible for me, so I assume it fixes it.

Please use the information referenced in the issue above to give the pre-release a try.
