### ISSUE TITLE
Light theme for plugin while using Dark theme in Idea

### ISSUE THREAD

**Issue by HenrikSkriver** [docToolchain/diagrams.net-intellij-plugin#106]
Hi
I am a long time user of Idea and Draw.io and I was very happy to come across your plugin.
I am running Idea 2021.2.2 UE and Diagrams.net Integration plugin 0.1.11 and using MacOS with Dark Theme.

Normally when running Draw.io desktop version, I am using the ligh theme but using the Dracula Theme in Idea.
So when I installed your plugin, the existing diagrams I have made, now appear with a dark background and changed colours in line with the Idea theme.
That does not result in diagrams which can be used.

Instead of changing and redoing my diagrams, is there anyway I can still use the light theme for your pluing while running the Dracula theme in Idea?

Thank you in advance.

**Comment by ahus1** [comment]
Hi @HenrikSkriver, 

in the IntelliJ settings, you can change the theme of the editor. See below for a screenshot. 

![image](https://user-images.githubusercontent.com/3957921/145676744-9939434c-b1c4-4961-b221-8f73858c2df4.png)

Please let me know if this solves your issue.

**Comment by ahus1** [comment]
Closing this issue after inactivity. Please comment if a question remains.

**Comment by jbeluch** [comment]
This happened to me as well. In addition to colors, it modifies the border the svg was exported with. Export from draw.io as "light" theme svg with a 100px border.

The workaround above fixes the lines/background issue, however the border is still stripped.

 I feel the plugin should never modify the svg or is this an issue with the underlying viewer?
