### ISSUE TITLE
Files not opened with Diagrams.net editor, just xml

### ISSUE THREAD

**Issue by kevinbeal** [docToolchain/diagrams.net-intellij-plugin#148]
I've installed the plugin, restarted, tried all the different extensions that are supported, and the diagram  editor never opens when I open the file. It just shows the xml for the file.

![Peek 2022-05-11 08-38](https://user-images.githubusercontent.com/855252/167890393-5569e8f8-598b-4e91-b951-7089898829ab.gif)

**Comment by rdmueller** [comment]
Thanx for reporting this.
Please take a look at the lower left border of your editor. It might be that there are two tabs - for the diagram editor and the XML view.

Sometimes, the XML view is opened first and we haven't found a way to modify this behaviour.

**Comment by kevinbeal** [comment]
Yep. That was it. :stuck_out_tongue: 
![image](https://user-images.githubusercontent.com/855252/168147593-259a517b-e56d-4112-b8f5-6990aad6aac8.png)
