### ISSUE TITLE
Auto save doesn't work with emojis

### ISSUE THREAD

**Issue by alex-semenk** [docToolchain/diagrams.net-intellij-plugin#152]
Diagram auto save functionality doesn't work in Intellij IDEA. Also I can't find an option to save the file manually. I am using drawio.svg format.

**Comment by rdmueller** [comment]
hm. I am still on 2022.1.1 Ultimate. let me do some tests...

**Comment by alex-semenk** [comment]
It's probably related to my diagram. I have tried to create new diagram from scratch and it saves correctly. I will my upload diagram example shortly.

**Comment by rdmueller** [comment]
ok, just did a quick check with my 2022.1.1 version. works with these filename/types:

```
image::demo.dio.png[]

image::demo.dio.svg[]

image::demo.drawio.svg[]
```

no I run an update...

do you have special characters in your file name?

did you create the diagrams within intellij?

**Comment by alex-semenk** [comment]
Yep, it seems to be related to emojis which I use in diagram. Here is an example.

![example drawio](https://user-images.githubusercontent.com/5796601/174637644-cf8d535f-d40d-487a-a693-a58093eb08cb.svg)

**Comment by rdmueller** [comment]
interesting finding - utf-8 characters (Umlauts) seem not to be a problem, but emojis are...

**Comment by alex-semenk** [comment]
Hi! 👋 I have just verified emojis on my latest Intellij IDEA Ultimate version 2022.2.3 and it works as expected now 👌 So I assume it could be some bug in previous versions of Intellij IDEA? Anyway it looks to work perfectly now, so I believe we can close the issue 🙂

**Comment by rdmueller** [comment]
Thanx for the feedback and happy diagramming 🤣
