### ISSUE TITLE
Pycharm integration

### ISSUE THREAD

**Issue by jhameier** [docToolchain/diagrams.net-intellij-plugin#167]
Tried this in Intellij (Ultimate & Community), works good. Would be nice to have it available in Pycharm.

**Comment by ahus1** [comment]
There's an automatic check running on the JetBrains marketplace: https://plugins.jetbrains.com/plugin/15635-diagrams-net-integration

It classifies this plugin to run on PyCharm Professional, PyCharm Community, PyCharm Educational and several other JetBrains IDEs.
