### ISSUE TITLE
Intellij 2022.2.1 does not render drawio ext files

### ISSUE THREAD

**Issue by nlidevs** [docToolchain/diagrams.net-intellij-plugin#178]
Opening drawio type files shows only xml text and does not render the graphical view.

png and svg formats are rendered correctly.

Diagrams.net Integration v0.1.12

![image](https://user-images.githubusercontent.com/99645279/201147903-47a2867b-d249-4309-b871-3d939d7e0ed1.png)

**Comment by ahus1** [comment]
Thanks for letting us know and sorry this didn't work for you. 

Can you please share the complete file name? Maybe we missed some file extension. 

Thanks!

**Comment by ahus1** [comment]
The next version of the plugin will look into XML files to see if they are drawio files. The current version requires them to be end with for example ".xml.drawio". Will comment here once the new version is available.

**Comment by ahus1** [comment]
The new version 0.1.13 is now available as a pre-release that includes this change. Please give it a try if it works for you.

The pre-release of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.
