### ISSUE TITLE
[0.1.13] Recognizes wrong xml as Drawio (pom.xml)

### ISSUE THREAD

**Issue by krissrex** [docToolchain/diagrams.net-intellij-plugin#179]
Hi, after the latest update (`0.1.13`), it picks up wrong files as diagrams.

To reproduce, create any xml file with this content:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
</project>
```

![image](https://user-images.githubusercontent.com/7364831/201928203-fea4507c-25c3-4cc8-9f2d-00696a54ccdc.png)

It thinks it is a drawio diagram.

**Comment by ahus1** [comment]
Thanks for reporting this, and I'm sorry that I have broken the functionality. Please downgrade to the previous version, and I'll provide a fix soon.

**Comment by ahus1** [comment]
There is now a pre-release 0.1.14 which should fix this. I'd be happy if you could give it a try.

The pre-release of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.

**Comment by krissrex** [comment]
Thanks you, it seems to work 👍 My pom.xml is not picked up as a diagram.

**Comment by ahus1** [comment]
Thanks for letting me know. I now promote the pre-release to a regular relase.
