### ISSUE TITLE
v0.1.12 stopped rendering in WebStorm 2022.2.3 

### ISSUE THREAD

**Issue by dkrantsberg** [docToolchain/diagrams.net-intellij-plugin#180]
The plugin initially worked in WebStorm, then all of a sudden it stopped rendering diagrams and displays just XML

<img width="869" alt="image" src="https://user-images.githubusercontent.com/1305115/202014626-75f2baa3-3fad-4f9b-b705-043736cfa437.png">

Plugin version: 0.1.12
WebStorm 2022.2.3 
MacBook Pro M1, macOS 12.6.1 Monterey

**Comment by ahus1** [comment]
Thanks for reporting this. Could you please look at the bottom of the editor window, There should be two tabs for the two editors ... can you switch to diagrams.net editor there?

![image](https://user-images.githubusercontent.com/3957921/202022624-1254c02e-e13a-4254-9d67-d8e33b6dc000.png)

**Comment by dkrantsberg** [comment]
I actually just figured it out and was about to delete this issue. Thanks!
