### ISSUE TITLE
Moving the canvas is very slow

### ISSUE THREAD

**Issue by adongguo** [docToolchain/diagrams.net-intellij-plugin#211]
Moving the canvas through the mac's trackpad, the canvas moves very slowly, with a lag.

version:
GoLand 2022.3.3
Build #GO-223.8836.34, built on March 8, 2023

**Comment by rdmueller** [comment]
Do you only experience this was in the plug in? Or also official draw.io app?
To be honest I think this is more problem of draw.io and hopefully not to plug in.

**Comment by adongguo** [comment]
only experience this in the plug in. The desktop and web versions are smooth.

**Comment by ErikHovhannisyanAmotek** [comment]
Have the same problem. I rolled back to version 0.20

**Comment by ahus1** [comment]
This is probably a duplicate to #212. Please follow the other issue for a workaround and any upcoming fixes.

**Comment by reva** [comment]
@ahus1 For what it's worth, this is not fixed with 0.2.2. (IntelliJ Ultimate 2023.1, macOS here). Setting `ide.browser.jcef.diagramsNet.osr.enabled` to `false` in the "Registry" as suggested in #212 fixes the problem for me.
