### ISSUE TITLE
Options when creating a new document

### ISSUE THREAD

**Issue by ellipticview** [docToolchain/diagrams.net-intellij-plugin#22]
When creating a new filename (i.e. creating a new diagram) in the Asciidoc file, it would be nice to have a dialogue that allows you to:
* Choose from templates (like the File>New of draw.io), or
* Choose to copy an existing file. Opening a file-chooser dialogue would be sufficient for this option. Nice if it filters on the same extension (i.e. svg or png)

**Comment by hediet** [comment]
Additionally to this, it would be cool if the default template could be remembered so that you don't need to select the same template every time and the dialog is only shown when needed.

**Comment by ahus1** [comment]
This has been implemented as part of issue #48 in the plugin version 0.1.6. Closing as a duplicate.

To use it, choose "File | New | diagrams.net File" 

No additional changes were made to copy an existing file, as this is already possible with copy/paste of files.
