### ISSUE TITLE
Created editable png can't be rendered

### ISSUE THREAD

**Issue by jvmlet** [docToolchain/diagrams.net-intellij-plugin#226]
`Add` -> `Editable PNG file`->...
The created png file is indeed editable , but can't be opened neither in `ImageFileEditor` tab neither in system  image viewer.

![image](https://github.com/docToolchain/diagrams.net-intellij-plugin/assets/6664858/e2a9c431-b5b0-4c94-9cd8-030450171228)

Rider `2023.1.2` , Windows 10

**Comment by ahus1** [comment]
I gave it a try with the latest version, please provide the image to further analyze it, or additional logs. Thanks!
