### ISSUE TITLE
only empty page

### ISSUE THREAD

**Issue by stleusc** [docToolchain/diagrams.net-intellij-plugin#262]
I see tha tabls at the bottom 
![image](https://github.com/docToolchain/diagrams.net-intellij-plugin/assets/1132106/6c41a6b5-6914-4721-af72-ffa3c2055679)
but the editor page is blank. xml page contains the XML.
No error message!
Latest 2023.2.1 Canary 12 and plugin 0.24

Any ideas?

**Comment by unshare** [comment]
Try installing [JavaFX Runtime for Plugins](https://plugins.jetbrains.com/plugin/14250-javafx-runtime-for-plugins)

**Comment by ahus1** [comment]
This might be similar to #298. I added a possible workaround there. Please have a look at that issue.
