### ISSUE TITLE
Please allow to select Light / Dark theme independently on the IDE settings

### ISSUE THREAD

**Issue by stefansimik** [docToolchain/diagrams.net-intellij-plugin#284]
I would like to ask for new feature:
Let's allow to select the theme (Ligh / Dark) independently from the IDE settings.
I like to have dark theme for coding, but creating diagrams in black is very unreadable.

That's the only reason, I have to fall back to original desktop app - just to see the diagrams clearly = in light theme.

Thank you in advance for your help.

**Comment by ahus1** [comment]
Thank you for reporting this. Please change the theme in the IDE's settings. Search for "diagrams.net" find them: 

![image](https://github.com/docToolchain/diagrams.net-intellij-plugin/assets/3957921/9a60f728-e1de-47e9-91dc-5059781e9724)

**Comment by stefansimik** [comment]
Thank you 💚
I tested and it works great 👍

Best
Stefan

**Comment by ahus1** [comment]
Happy to help!
