### ISSUE TITLE
White editor window in intellij 2024.1.1 on fedora 40 wayland

### ISSUE THREAD

**Issue by leubedane** [docToolchain/diagrams.net-intellij-plugin#298]
I love this extension. It is great to edit my diagrams in my favorite IDE. Unfortanetly I got a white tab, when I am trying to open an editable png file:
![image](https://github.com/docToolchain/diagrams.net-intellij-plugin/assets/20238253/9aa029b9-eeea-4c68-a87d-1864849c3771)

I tried to checkout the logs, but there are no log entries. What can I do to provide you more information :-).

**Comment by ahus1** [comment]
I'm sorry to hear this is broken for you. I had a similar problem reported for another plugin here https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/1610, and maybe this the same cause. 

I raised this issue: https://youtrack.jetbrains.com/issue/IJPL-148653/Preview-of-Markdown-stays-empty-after-hostname-change

The issue includes a workaround. Please let me know if this works for you. I'll see that the next version of this plugin includes the workaround.

**Comment by ahus1** [comment]
There is now pre-release v0.2.5 which includes a fix. Please give it a try if it fixes your problem.

The pre-release of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.

**Comment by leubedane** [comment]
Wow I'm impressed with your fast reaction :+1: . I didn't get a notification about your comment. I tried it today and it worked with the pre-release version. Now I can edit the picture again. Thank you very much.

**Comment by ahus1** [comment]
Great to hear that it works. This gives me more confidence to publish it to the marketplace next week.

**Comment by ahus1** [comment]
BTW, if you haven't done so, please up-vote the upstream issue so it will get eventually fixed. Thanks!
https://youtrack.jetbrains.com/issue/IJPL-148653/Preview-of-Markdown-stays-empty-after-hostname-change
