### ISSUE TITLE
Javascript alert Error: Uncaught Class OrgChart.Annotations.CanBeNullAttribute is already defined

### ISSUE THREAD

**Issue by kjeldahl** [docToolchain/diagrams.net-intellij-plugin#301]
I keep getting this notification whenever I open a diagram in Rubymine.
Plugin version: 0.2.5
RubyMine 2024.1.1
Build #RM-241.15989.113, built on April 24, 2024
Runtime version: 17.0.10+1-b1207.14 aarch64

<img width="266" alt="image" src="https://github.com/docToolchain/diagrams.net-intellij-plugin/assets/19719/e9230370-47dc-43f9-948a-0963f5151dc0">

It does not seem to impact any functionality though.

**Comment by ahus1** [comment]
Can you please provide an example diagram where this happens?

**Comment by kjeldahl** [comment]
Sure, here is an empty one I just created as an "Editable svg file"

![Test](https://github.com/docToolchain/diagrams.net-intellij-plugin/assets/19719/51a8fc9b-a5b8-45d9-ada6-232b8ece9aeb)

**Comment by Glydric** [comment]
Same here for RustRover, but also lags a lot and is unusable

**Comment by michaelbeauchemin** [comment]
Seeing the same behavior (JavaScript Alert popup, odd coloring) within Intellij IDEA Ultimate EAP Build #IU-242.14146.16, built on June 1, 2024.

**Comment by Les-Fleming** [comment]
I am seeing the same on a newly created test.drawio file with IntelliJ IDEA 2024.1.4 (Ultimate Edition). Good Work all the same.

**Comment by ahus1** [comment]
I was able to find those error messages in the JCEF developer tools, although they never appeared in any part of the IDE or as a pop-up. 

Note to my future self: I found that since the diagrams.net upgrade to 20.8.16 I don't need to load the minified other parts of the application, as they will initialize themselves.

https://github.com/jgraph/drawio/blob/6bea84f05906233f552e20bc63e078763740a442/src/main/webapp/js/diagramly/App.js#L1084-L1091

This will be part of the next release of the pluign.

**Comment by ahus1** [comment]
There is now pre-release 0.2.6 available which includes a fix for this issue. Please give it a try and let me know if it works in your setups as expected. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.

**Comment by kjeldahl** [comment]
@ahus1 It is working. 👍  Thanks for looking into it. 
Will the pre-release plugin I installed be updated automatically when the new version is released or must I remove it manually?

**Comment by ahus1** [comment]
Happy to hear it now works as expected. 

> Will the pre-release plugin I installed be updated automatically when the new version is released

Yes, the next version will be installed automatically. IntelliJ will check for a higher version number in the marketplace and will prompt you for an upgrade once that is available.

**Comment by ahus1** [comment]
I'll publish the version 0.2.6 to the marketplace, and it will be available with in 1-2 business days once the new version has been approved be the JetBrains Marketplace team.
