### ISSUE TITLE
IDE freezes when huge XML file exists in project

### ISSUE THREAD

**Issue by bibermann** [docToolchain/diagrams.net-intellij-plugin#304]
PyCharm freezes (with high CPU usage) when I have a 6GB XML file in the project (even when marked as excluded).

Probably the extension tries to find out whether it's a diagram? This happens right after launching the IDE (when the file is just there, not even opened).

**Comment by ahus1** [comment]
I'm sorry to hear this happend to you. I'll fix it in the next version of the plugin. I'll restrict the auto-detection to XML files which are 10 MB the most.

**Comment by ahus1** [comment]
There is now pre-release 0.2.6 available which includes a fix for this issue. Please give it a try and let me know if it works in your setups as expected. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.

**Comment by bibermann** [comment]
> There is now pre-release 0.2.6 available which includes a fix for this issue. Please give it a try and let me know if it works in your setups as expected.
> 
> The pre-release of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases).
> 
> To try out a pre-release:
> 
> 1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
> 2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
> 3. Choose **Install plugin from disk...**.
> 4. Choose the downloaded file in the file selection dialogue.
> 5. Restart the IDE to activate the new plugin version.

I'm sorry that I could not find the time to try it out earlier; I just upgraded to the new release which solved the issue for me :) Thanks for the fast fix!

**Comment by ahus1** [comment]
Thanks for sharing!
