### ISSUE TITLE
Update Diagrams.net-Version

### ISSUE THREAD

**Issue by ahus1** [docToolchain/diagrams.net-intellij-plugin#43]
The current version of draw.io that the plugin uses seems to be v13.7.9 (October 2020). 

The most recent version seems to be 14.1.7 (Jan 2021). 

Time to update...

**Comment by rdmueller** [comment]
I guess we can close this with #65 , can't we?

**Comment by ahus1** [comment]
Yes, thanks for grooming the ticket list.
