### ISSUE TITLE
Why no support for svg extensions without drawio

### ISSUE THREAD

**Issue by sschuit** [docToolchain/diagrams.net-intellij-plugin#48]
I was wondering why there is no support for svg files without .drawio? Is there a technical limitation?

**Comment by rdmueller** [comment]
good question. I think it would break normal .svg support. Not every svg is a draw.io file but it would be opened as such.
But we migh be able to extend the plugin to check the contents of the svg.

This is the part where the could would have to be added:
https://github.com/docToolchain/diagrams.net-intellij-plugin/blob/main/src/main/kotlin/de/docs_as_co/intellij/plugin/drawio/editor/DiagramsEditorProvider.kt#L21

**Comment by sschuit** [comment]
Thanks for the info. For the moment i have a script that generates a symbolic link with the name.  Is there a certain tag inside the svg for drawio or is it the svg version?  Other option would to be a configuration option to enable with maybe a location filter.

**Comment by avdrovaart** [comment]
I had the same issue, is it possible to use the file associations configured in IntelliJ.
I added the *.svg to the editor and all the icons changed, but when i doubleclicked the file it opens in a text editor and not the diagrams plugin

**Comment by rdmueller** [comment]
Interesting. Just to understand the situation - why is it so important for you to work with `*.svg` files instead of `*.dio.svg` files?
(I will try to check teh contents of the file and decided based upon this how to open it.)

**Comment by avdrovaart** [comment]
We already have .svg files in the repository and some of us are using diagrams.net and other are using inkscape. And it doesn't seem right to change the extension of a file just that it opens with the plugin.

**Comment by ahus1** [comment]
Hi @avdrovaart - the situation where diagrams are edited with Inkscape and diagrams.net will lead to data loss,
as a diagrams.net diagram will contain an editable diagram in the diagrams.net format, and a read-only "rendered" SVG version as the same time. 
Diagrams.net will only read the editable part, and will then write the editable part plus a rendered SVG version. Inkscape will only read the part that is supposed to be read-only, and will change it.

This leads to the following situation: when a user edits a diagram create with diagrams.net within Inkscape, they will edit the supposed read-only SVG version and save their latest changes to the file. Depending on the SVG program you're using, the editable part of diagrams.net will be unchanged, or might be removed. Once a user of diagrams.net opens the file, they will only see the editable (old) content, and will overwrite the the SVG on their next change, as the read-only "rendered" SVG version is created from the editable diagram portion. 

Therefore I consider it important to keep extra extension for files that should be edited with diagrams.net and not with Inkscape. 
Therefore I vote for "keep extra extension" here.

**Comment by avdrovaart** [comment]
@ahus1 I agree that the extra extension is important to make the difference, but if someone else doesn't have the plugin it still no use to have the extra extension.
So the default extensions of the plugin should have the extra extensions, I can totally live with that, but if I configure IntelliJ to associate a certain file extension with a plugin (icon of the file changes to plugin icon) it should open with the configured-plugin and not with the old-plugin or default editor. 

It's just like reassigning a .mp3 file to open with Winamp. When you double click it you expect it to open with Winamp and not Itunes, MediaPlayer or whatever

**Comment by ahus1** [comment]
The next release of the plugin will auto-detect editable diagram.net diagrams in SVG and PNG format as long as they have they have a file extension of ".png" or ".svg". 

This is accomplished by peeking into the image file when such a file is opened.

No need configure the IDE. I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
Pre-release v0.1.6 is available from the GitHub releases of this plugin. It includes the changes for this ticket. 

Once it is approved by the JetBrains marketplace team, it will be available in the EAP repository of the plugin.
