### ISSUE TITLE
plugin doesn't work with EAP 2021.1 / "Please ensure JavaScript is enabled."

### ISSUE THREAD

**Issue by dannybloe** [docToolchain/diagrams.net-intellij-plugin#53]
Hi folks, 

Trying this plugin in latest version of WebStorm (EAP) but when I try to open a diagram it says:

```
Page could not be loaded. Please try refreshing.
Please ensure JavaScript is enabled.
```

I cannot find any information about how to get this to work Am I missing something?

Cheers, 
Danny

**Comment by rdmueller** [comment]
interesting. It should just work out of the box. Let me install webstorm and give it a try.

**Comment by rdmueller** [comment]
what I did:
- installed latest version of webstorm
- started it as free trial
- installed asciidoctor plugin (**is this maybe the problem?**)
- installed diagrams.net plugin
- created test.adoc file
- typed `image::test.dio.svg[]`
- alt+enter to create non existing `test.dio.svg`
- editor opened without problem

what did I do different from your setup?

**Comment by dannybloe** [comment]
I created a diagrams.net document online in Chrome and stored it locally. Then installed the plugin and opened it. I am running the EAP version:

**Comment by YoonAddicting** [comment]
It is probably an issue with the 2021.1 EAP versions, because I am encountering the same issue in PyCharm 2021.1 EAP Build #PY-211.6085.15, built on February 18, 2021, however it works fine with the very same files in Pycharm 2020.3.3 Build #PY-203.7148.72, built on January 27, 2021.

**Comment by rdmueller** [comment]
EAP could be the reason but would be surprising to me. I'll try to check this out

**Comment by ahus1** [comment]
I updated the IntelliJ Marketplace that the plugin supports 2020.3.* at maximum.

**Comment by ahus1** [comment]
Version 0.1.5 is available from GitHub releases, and soon (after JetBrains Marketplace team's approval) also from the JetBrains Marketplace.

**Comment by dannybloe** [comment]
I can confirm that it now works in WebStorm. Thanks all.
