### ISSUE TITLE
Predefined process looks bad in dark theme

### ISSUE THREAD

**Issue by penn5** [docToolchain/diagrams.net-intellij-plugin#62]
Switching IDE to dark theme means predefined process gets filled with white

![image](https://user-images.githubusercontent.com/5600962/111033680-537a5e80-840a-11eb-9ce5-ad9e63a10143.png)

**Comment by penn5** [comment]
Sorry, this appears to be my fault. I must have accidentally styled that node to be filled.

**Comment by rdmueller** [comment]
no, not your fault. There seem to be two colors in diagrams which change with the theme. This is somehow a problem, so I reopen theis issue, even it it still takes a while to resolve it... 😀

but thanx for taking care of the status!

**Comment by rdmueller** [comment]
I'll close this now because with #65 , it will be possible to switch themes independent from the intellij theme.
and btw: it seems that you get into less trouble if you use the predefined styles for boxes than to switch colors manually... at least, that's what I experienced
