### ISSUE TITLE
Is it possible to set theme?

### ISSUE THREAD

**Issue by NickRimmer** [docToolchain/diagrams.net-intellij-plugin#65]
Hi all, thank you for this integration! Looks really cool.
I would like to ask you, if it possible to choose light theme of Diagrams Editor with dark theme of IDE?

**Comment by rdmueller** [comment]
currently we don't have an options dialog, but this idea should be on our backlog. Thanx for raising it!

**Comment by dnltsk** [comment]
Found [this](https://github.com/docToolchain/diagrams.net-intellij-plugin/issues/3) in your Backlog.

Think I have the same feature request: Would like to have light themed Diagrams in dark themed IDE.

**Comment by ahus1** [comment]
@rdmueller @hediet - I made an attempt to solve this issue. Anyone wants to give it a test run?

**Comment by rdmueller** [comment]
yes, sure. I guess I will find some time tomorrow to give it a try.

**Comment by ahus1** [comment]
There's now a pre-release 0.1.8 for this plugin. I'd be happy if someone from the community can give it a try and could provide feedback if it works as expected. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/docToolchain/diagrams.net-intellij-plugin/releases). 

To try out a pre-release:

1. Download the new release file `diagrams.net-intellij-plugin-xx.xx.xx.zip` from the _Assets_ section of the release.
2. Go to menu **File | Settings... | Plugins | Gear Icon** (⛭).
3. Choose **Install plugin from disk...**.
4. Choose the downloaded file in the file selection dialogue.
5. Restart the IDE to activate the new plugin version.

**Comment by rdmueller** [comment]
Sorry, took a bit longer to give it a try.
It work like a charm. I expected problems with the automatic change for some colors (black lines in the light theme have to turn to white etc.) but no problems encountered. Colors seem to be always readable...

Great work!

**Comment by rdmueller** [comment]
I just managed to get an ugly effect, but I guess this is how the themes work:

Sketch Theme:
![image](https://user-images.githubusercontent.com/1856308/120933455-8460eb80-c6fa-11eb-8ff8-5c00b950e4be.png)

I changed the background color of the left box to a light gray via a style and the text color of the database to a dark gray (nearly black) directly as a font color

Dark-Theme:
![image](https://user-images.githubusercontent.com/1856308/120933430-6f845800-c6fa-11eb-83f6-17c311aeeb21.png)

As you can see, the colors of the left box are not changed at all when I switch to the dark theme, but the colors of the database icon are inverted - all but the changed font color. This makes the text unreadable.

I am sure that this is not a problem of the plugin but of the themes themselve.
I guess it will only appear if you change colors directly for font or background but will not have any effect if you change them via the styles.

![image](https://user-images.githubusercontent.com/1856308/120933684-7f506c00-c6fb-11eb-9cd3-f45e1c28b1cb.png)

**Comment by ahus1** [comment]
@rdmueller I think the effect you see might be the primary reason people want to switch themes... 😄

**Comment by ahus1** [comment]
I promoted this pre-release to a release. It should be available from the JetBrains marketplace within 2 days after it has been approved by the JetBrains marketplace team. 

As there is AFAIK nothing left to do for this issue, I close it.
