### ISSUE TITLE
can it run in Pycharm

### ISSUE THREAD

**Issue by ciciandjojo** [docToolchain/diagrams.net-intellij-plugin#67]
can it run in Pycharm

**Comment by ahus1** [comment]
Yes, it works with PyCharm. The JetBrains marketplace lists the current version to be compatible with: 

```
PhpStorm — 2020.2+

Rider — 2020.2+

IntelliJ IDEA Educational — 2020.2+

WebStorm — 2020.2+

DataGrip — 2020.2+

Android Studio — build 202.0+

AppCode — 2020.2+

IntelliJ IDEA Ultimate — 2020.2+

PyCharm Educational — 2020.2+

IntelliJ IDEA Community — 2020.2+

PyCharm Professional — 2020.2+

GoLand — 2020.2+

PyCharm Community — 2020.2+

RubyMine — 2020.2+

MPS — 2020.2+

CLion — 2020.2+
```

**Comment by ahus1** [comment]
(as the question has been raised in a different thread: please read it as "supported from 2020.2 onwards" - this includes also 2021.*)

**Comment by ahus1** [comment]
I close this issue as there hasn't been a comment for several months. Please comment again to re-open the issue.
