### ISSUE TITLE
Update for latest version of IntelliJ

### ISSUE THREAD

**Issue by bitbonk** [docToolchain/diagrams.net-intellij-plugin#70]
About two months ago, Rider 2021.1 Since then I get the following error:

> Plugin error: Plugin 'Draw.io Integration' (version '0.1.1') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is RD-211.7142.19

Are you planning an upgrade?

**Comment by ahus1** [comment]
The current version of the plugin on the marketplace is v0.1.5. Can you please try to trigger you IDE to update the installed plugins?
The marketplace reports for v0.1.5 the following versions to be compatible: 

![image](https://user-images.githubusercontent.com/3957921/116226335-216f5280-a753-11eb-8ba3-29c376348289.png)

**Comment by bitbonk** [comment]
> 12:10	Plugin error: Plugin 'Draw.io Integration' (version '0.1.1') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is RD-211.7142.19
> 12:15	No IDE or plugin updates available

The product screenshot shows it is compatible with the 2020 wave of products. But the current version of Rider is already 2021.

**Comment by bitbonk** [comment]
It looks like the issue was that you [renamed the plugin](https://github.com/docToolchain/diagrams.net-intellij-plugin/commit/710449da77e7f9c2125f7e16445542ceac4f0b05). That's why I didn't get the updates. So I uninstalled the old _"Draw.io Integration"_ plugin and installed the new _"Diagrams.net Integration"_. Now it works.

**Comment by ahus1** [comment]
Oops, you're right! We renamed it just before we finally published it to the store. Sorry for the confusion. Glad you found it!
