### ISSUE TITLE
Uses offline version of Draw.io by default?

### ISSUE THREAD

**Issue by vassudanagunta** [docToolchain/diagrams.net-intellij-plugin#71]
The [feature list for the VSCode Draw.io plugin](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio) states: 

> Uses an offline version of Draw.io by default.

Is this also true of this Jetbrains plugin?

**Comment by rdmueller** [comment]
yes. @hediet, the author of the VSCode plugin implemented it the same way for the intellij plugin

**Comment by vassudanagunta** [comment]
cool!

**Comment by ahus1** [comment]
plugin description updated
