### ISSUE TITLE
markdown plugin shows blank page

### ISSUE THREAD

**Issue by ahus1** [docToolchain/diagrams.net-intellij-plugin#87]
I have a similar issue, but once the draw.io plugin is enabled, the `official Jetbrains markdown` plugin doesn't even load anything at all and it only shows a blank white window. This at least happens on CLion, most likely on other Jetbrain's products too.

_Originally posted by @hiradyazdan in https://github.com/docToolchain/diagrams.net-intellij-plugin/issues/83#issuecomment-882033829_

**Comment by ahus1** [comment]
Hi  @hiradyazdan, I moved your comment over here as this seems unrelated to issue #83: The preview displayed in the other scenario, the UI froze/lagged for some seconds only when I reproduced it.

To analyze the white preview I need some additional information to investigate further: 

* version of your IDE
* installed plugins and versions
* a minimal example markdown text that shows the blank preview

You can copy this information from "Help | About". The latest 2021.2 versions have a "Copy" button, earlier versions had an icon that appeared when hovering over the about screen. Once you copied the contents to the clipboard, please paste them here as a comment.

Thanks,
Alexander

**Comment by hiradyazdan** [comment]
Hi @ahus1. Thanks for following this up. So, here are the details as requested:

- CLion 2021.1.3 on Windows 10
- Jetbrains s.r.o Markdown 211.7142.37
- Diagrams.net Integration 0.1.10

Some of the other plugins were added after the issues were ocurring with the `draw.io` and `markdown` plugin, so if they may look suspecious because of ther type, they don't necessarily contribute to the issue here.

```cmd
CLion 2021.1.3
Build #CL-211.7628.27, built on July 1, 2021
Licensed to --
Subscription --.
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: ru.phism.intellij.unreal (0.1), Batch Scripts Support (1.0.12), CMD Support (1.0.5), GLSL (1.19), IdeaVIM (0.69), com.google.idea.gn (0.1.3-2-g699ba01), com.jfrog.conan.clion (1.2.0), com.zero9178 (2021.1.8), de.docs_as_co.intellij.plugin.diagramsnet (0.1.10), in.xiv.cs (0.1), it.czerwinski.intellij.wavefront (1.0.1), org.editorconfig.editorconfigjetbrains (211.6693.114), mobi.hsz.idea.gitignore (4.1.0), Docker (211.7442.9), com.intellij.kubernetes (211.7442.27), org.toml.lang (0.2.151.3997-211), quickturnstudio.sdk.language.qss.QtStyleSheetsEditor (0.9.2), com.intellij.plugin.adernov.powershell (2.0.7), com.zxy.ijplugin.wechat-miniprogram (3.5.6), ru.adelf.idea.dotenv (2021.2), nl.rubensten.texifyidea (0.7.8), com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.1), org.rust.lang (0.4.151.3997-211)
```


![Screenshot 2021-07-20 201811](https://user-images.githubusercontent.com/5919776/126382803-8011683d-ddf2-47b0-929a-27acf9fffb13.png)

**Comment by ahus1** [comment]
Apparently I introduced this issue in #65 where I cleared the theme support. I must not clear the scheme handler factories. 

Once I didn't do that, the previews render again. 

The fix is available as part of release 0.1.11. It's available now from GitHub releases, and will soon be available from the JetBrains Marketplace.

**Comment by hiradyazdan** [comment]
@ahus1 Thank you. It's working perfectly fine now.

**Comment by ahus1** [comment]
Glad to hear it is solved. I'm sorry my original change caused you troubles. Thanks for tracking this down to this plugin.
